### ISSUE TITLE
Fishtrap fängt nichts

### ISSUE THREAD

**Issue by Leichenengel** [Uraneptus/Fishermens-Trap#13]
Hallo auch.

Ich dachte mir, da es in den Kommentaren bei curseforge doch etwas schleppend läuft, verlagere ich das Ganze jetzt doch mal nach hier. Der Einfachheit halber kopiere ich einfach das, was bislang da schon an Kommunikation gelaufen ist und füge dann noch ein paar Infos an, wie z.B. meine Modliste.

------------------------------------------------------------

>Leichenengel: So I'm using the latest version for 1.20.1 on Forge. I have my base next to a river biome, so I built a little landing stage leading into the river biome. I placed some traps there in the vicinity of the landing stage and of course underwater. The traps are surrounded by at least 4 blocks of water each (some are "hanging" at the logs that support the stage). I've stuffed them with a stack of sweet berries and beetroot to catch salmon and cod and left them alone for a few minecraft days working on my farm nearby (so the chunk with the traps was loaded). Nothing was caught and the bait stacks didn't deplete either. I've tried adding biome tags to the mod and even tried the #is_overworld tag. No luck. The water body of the river biome spawns squids and fish mobs and even ducks from another mod that are supposed to only spawn in river biomes. So what is happening here? I use the Forge Version 47.1.43 due to Optifine needing that version.

>Uraneptus: Hmm that's weird. Are all fishtraps hanging? Or are some just placed on a block?

>Leichenengel: There are two of them hanging (connected to 1 block with one of the longer sides leaving the botton, the 2 shorter sides and the top open to water blocks)

3 are placed down on blocks with the bottom. 1 on wood logs (of the landing stage support structure) and 2 on sand blocks belonging to the river ground.

None of them Caught anything yet and I'm on Day 300+ in that world having been in the vicinity of the traps half of the time building and tending to my farm - also I have the chunk update distance set to 20 since I have a large farm and want half of it to be constantly loaded when I'm at my main base so the crops I need most update regularly...which also applies to the traps as they are placed within 2 chunks of my main building.

I do admit, that I used Biomes o Plenty for more biomes at world gen, but as well the F3 screen as also Xaeros Minimap classifies the biome the Traps are placed in as "River" and as mentioned Ducks from the Duckling Mod also spawn there which are also only supposed to spawn in River Biomes.

-----------------------------------------------

Seither hat sich die Liste an Mods die ich nutze etwas verändert. Statt Biomes o Plenty nutze ich jetzt Terralith und hab ne neue Welt damit generiert. Terralith nutzt vanilla-eigene Blöcke um neue, vanilla-nahe Biome zu erstellen und die vanilla-eigenen Biome zu verbessern. Auch hier zeigen der Debug Screen und Xearos Minimap in River Biomen auch River Biome an. Ich siedle allerdings in einem von den Terralith Biomen, hab jedoch drauf geachtet ein River Biom in Basisnähe zu haben.

Anbei noch die Modliste. Womöglich ist da irgendwas bei, was zu Inkompatibilitäten führt. Vermutlich muss ich irgendwas im Code ändern, aber ich bin überhaupt kein Programmier-Genie. Das mit dem #is_overworld in der betreffenden json im mod hat ja irgendwie nicht geklappt.
Vielleicht kriegen wir das irgendwie zum Laufen, da mir zum Angeln die Geduld fehlt und ein Autofishing Mod nur dazu führt dass ich abkratze wegen den Phantomen. Der Loot interessiert mich gar nicht mal so sehr, eher die Fische wegen Kochen ^^

LG,

Rike

PS: Hab leider keine spoiler-funktion gefunden ^^

------------------------------------------------

_- ametrin 0.1.2
- appleskin 2.5.1+mc1.20.1
- architectury 9.1.12
- automaticdoors 4.4
- badpackets 0.4.3
- biggerstacks 1.20.1-0.0.3
- block_variants 5.0
- butchersdelight 1.20.12.0.8
- butchersdelightfoods 1.20.11.0.2
- climbladdersfast 4.0-1.20.1
- cloth_config 11.1.106
- collective 6.66
- connectedglass 1.1.8
- crabbersdelight 1.1.2
- create 0.5.1.f
- create_sa 2.0.4.
- denseores 1.2.1
- doubledoors 5.0
- duckling 3.0.0
- easyanvils 8.0.1
- endersdelight 1.0.3
- everycomp 1.20-2.6.16
- extended_villager_trades 2.0
- farmersdelight 1.20.1-1.2.3
- ferritecore 6.0.1
- fishermens_trap 2.1.1
- flywheel 0.6.10-7
- forge 47.1.43
- funnybagelmod 1.0.0-1.20.1
- geckolib 4.2.4
- geophilic 2.0.0-mc1.20u1.20.1
- hardernaturalhealing 46.1.13
- heyberryshutup 1.20.1-2.0.4
- hoetweaks 3.2
- incendium 5.3.3
- jei 15.2.0.27
- keepmysoiltilled 2.0
- leavemybarsalone 8.0.0
- mcwbridges 2.1.1
- mcwdoors 1.1.0
- mcwfurnitures 3.2.0
- mcwpaintings 1.0.4
- minecraft 1.20.1
- mixinextras 0.2.0-rc.3
- mobneutralizer 1.20.1-v1
- modernfix 5.9.2+mc1.20.1
- moonlight 1.20-2.8.60
- mooshroomtweaks 3.2
- naturals 1.0.0
- nethersdelight 1.20.1-4.0
- packedup 1.0.30-dev
- paintings 11.0.0.0
- phantomslma 0.1.1
- purified_flesh_mod 1.3.0
- puzzlesaccessapi 8.0.7
- puzzleslib 8.1.8
- reclaimed_rocks 0.2-1.20.1
- repurposed_structures 7.1.7+1.20.1-forge
- rightclickharvest 3.2.3+1.20.1-forge
- simplybackpacks 1.20.1-2.1.5-build.51
- stackrefill 4.0
- storagedrawers 12.0.2
- supermartijn642configlib 1.1.8
- supermartijn642corelib 1.1.15
- terrablender 3.0.0.169
- terralith 2.4.8
- tramplestopper 5.0.0+mc1.20.1
- treasuredistance 1.20-1.2
- treeharvester 8.2
- trenzalore 3.3.9
- twigs 1.20.1-3.1.0
- waila 8.4.0
- wthit 8.4.0
- xaerominimap 23.8.2_

**Comment by Uraneptus** [comment]
Hi, danke dass du mir hier nochmal geschrieben hast, über curseforge Kommentare ist sowas immer ein bisschen kompliziert! Ich werd heute oder morgen mal die modliste laden und mir das genauer anschauen. Meinst du, du könntest mir noch deinen world seed und die Koordinaten von dem genannten Fluss schicken?

**Comment by Leichenengel** [comment]
Welt-Seed: 13263952657891

Koordinaten der Base: -578, 67, 1065

Koordinaten des River Biomes (mittendrin): -606, 55, 1128

Ich hab die 2 Fallen auf den Böden neben diesem Koordinatenpunkt aufgestellt - je rechts und links eine. (Blickrichtung Westen oder Osten)

Modeinstellungen sind auf Standard

Random Tick Speed bei Generierung der Welt 10 statt 3 (damit die Pflanzen schneller wachsen und ich keine ewig große Farm brauche)

Chunk Ladedistanz (Simulation Distance): 20

Chunk Renderdistanz: 10

**Comment by Uraneptus** [comment]
Vielen Dank, ich schau mir das später einmal genauer an!

**Comment by Uraneptus** [comment]
Okay also ich hab die Fishtraps jetzt hier platziert.
![image](https://github.com/Uraneptus/Fishermens-Trap/assets/50745606/c017b3fa-b013-4f99-8993-7b9e1a0fd4e5)

Bei wird allerdings Fish gefangen
![image](https://github.com/Uraneptus/Fishermens-Trap/assets/50745606/cac6fd03-8992-45b3-9583-2ce9a7638df5)

Ich stand da unten für ein paar Minuten:
![image](https://github.com/Uraneptus/Fishermens-Trap/assets/50745606/2035950b-4d73-48b0-82dd-4d21ee33a14c)

Ich muss aber auch sagen, dass ich in der Config die Ticks geändert habe um das ganze besser zu testen.
Könntest du eventuell auch einmal die Config bearbeiten und die benötigten Ticks reduzieren?

**Comment by Leichenengel** [comment]
Ja sicher, wenn du mir sagst was du wo eingetragen hast?

Ich glaube ich hab die Tick Rate schon reduziert. Als Default für den Max Wert ist 8000 angegeben, bei mir steht da 4000 und bei dem Min Wert steht 2800. Bei beiden steht im Tooltip dass der Wert größer oder kleiner als der andere sein muss. Das ist hier soweit ich sehe der Fall.

Ich weiß nicht, ob die Random Tick Speed Rate auch was damit zu tun hat. Aber selbst wenn die im Mod vorkonfigurierten Default Werte zu groß sind, sollte sich ja dennoch nach mehreren MC-Tagen ein Erfolg einstellen, solange man an den Traps nicht rumbastelt, oder?

**Comment by Uraneptus** [comment]
Ich hab zum testen 800 & 480 benutzt. Mit den Werten die du hast (also max 4000) sollte die mindestens alle 3 minuten und 20 sec etwas fangen. Wenn du es ganz schnell haben willst, würde ich 80 & 48 benutzen, das ist was ich zum debuggen normalerweise benutze. 
Könntest du eventuell auch mit relativ geringen Werten einmal ganz nah bei der Fishtrap stehen? Somit können wir schauen ob überhaupt irgendwas jemals gefangen wird

**Comment by Leichenengel** [comment]
Also alle 3,5 Minuten fängt die nix und mit bei den Fallen rumstehen hab ichs schon versucht bei aktuellen Einstellungen. 10-15 Min idle da rumgestanden während ich inner Küche war. als ich wiederkam war nix passiert. Ich versuch noch mal mit 800 und 480 .

EDIT: Also hab jetzt deine Werte (800&480) in die Config eingetragen und MC neugestartet. Fallen weg gemacht und wieder hingesetzt und neu bestückt. Hab jetzt 15 Minuten da rumgestanden und nebenbei Bau-Inspirationen gegoogelt. Keine Fische. Könnte es damit zu tun haben, dass ich zur Zeit auf Peaceful spiele? Sollte eigentlich nicht, da Fische ja passive Kreaturen sind und soner Falle sollte der Schwierigkeitsgrad wurscht sein. Ansonsten könnte es nur noch an den Einstellungen liegen die ich gemacht habe was das Generieren der Welt und die Gamerules angeht. Wobei das auch nur einige wenige sind die nicht default sind. Explosionen zerstören keine Items, kein Fallschaden und kein Ertrinken (Es sind soo viele Höhlen unter Wasser schon im frühen Spielstadium da erschien mir das sinnvoller als ne Ewigkeit warten bis ich Verzauberungen oder Tränke habe. Finde diese überfluteten Höhlensysteme eh blöd ^^). Weiterhin halt ein Random Tick Speed von 10 (statt Default 3) und ansonsten keine Pillager Patrullien (die anfangs nerven beim Bauen und außerdem hat meine Welt gefühlt in jedem Biom 4 Dörfer....). Der rest ist Standard, denk ich.

**Comment by Uraneptus** [comment]
Ich muss ganz ehrlich sagen, ich bin sehr verwirrt 😅
Ich werd mal den Abend lang drüber nachdenken was hier der Grund sein könnte!
Könntest du eventuell alle mods und deine Welt als zip Datei irgendwo hochladen und mir den link zum runterladen schicken? Dann kann ich mir sicher sein, dass ich beim Testen dieselben Mods und Welteinstellungen habe!

**Comment by Uraneptus** [comment]
Die Einstellungen, die du genannt hattest sollten eigentlich keine Rolle spielen, aber man weiß ja nie!

**Comment by Leichenengel** [comment]
Uhh irgendwo hochladen ist gut....dat sind fast 70 MB - hab keinen Webspace wo ich das mal eben hintun könnte (EDIT 1: obwohl ich glaub ich weiß da was, das kann ich versuchen). Die Welt...ich hab ehrlich gesagt noch nie Welten geteilt. Muss ich da den Ordner mit dem Weltnamen in "saves" zippen? Ich nehm mal an die Configdateien willst du auch haben so wie sie bei mir sind, mh?

EDIT 2: Okay also was ich zippen muss weiß ich nun, hab einfach gegoogelt, aber on du die Config-Dateien auch haben willst, müsste ich schon wissen, denn wenn, dann pack ich alles in eine Zip-Datei (natürlich getrennte sub-Ordner ^^). Heute aber wohl nimmer, gehe gleich schlafen.

**Comment by Uraneptus** [comment]
Ja config bitte auch! Hatte ich vergessen zu erwähnen.
Gute Nacht! ^^

**Comment by Leichenengel** [comment]
Hab alles vorbereitet. Würde den Dienst WeTransfer.com benutzen (den haben wir früher in der Ausbildung benutzt um die großen Druckdateien an unsere Druckerei zu senden, ist also sicher), dazu brauche ich eine Empfänger E-Mail Adresse. Hab zwar ne Dropbox, aber  der Account ist ewig alt und das PW ist verschütt gegangen. Hab noch bissel Klarschiff gemacht an meiner Base, falls du dich umsehen willst, daher bin ich noch auf. Die Stelle mit den Fallen hab ich mit Laternen unter Wasser markiert - ist also am besten im Dunkeln zu sehen.

**Comment by Uraneptus** [comment]
Klingt gut! Als Email kannst du meine mehr oder weniger Geschäftsemail `uraneptus0@gmail.com` nutzen!

**Comment by Leichenengel** [comment]
Alles klar, ZIP ist versendet. Dann bin ich mal gespannt wie das bei dir läuft mit meiner Welt. Wenn es bei dir funktioniert, dann fress ich n Besen x-) Ach ja: Guten Morgen :)

Wenn du dich umsehen magst tu das ruhig, ist drinnen bis auf 2-3 Räume noch alles sehr karg, Einrichtung kommt so peu a peu wie die Materialien da sind :D Ich empfehle dir jedoch das Resource Pack zu installieren das ich beigefügt habe, sonst sieht der Kram vermutlich arg wunderlich aus (farblich und mustertechnisch). Weiterhin ist ein Resource Pack dabei (Fractal Paintings) das ist ein Muss, da das zu dem Paintings Mod gehört bzw von dem eingelesen wird. Du kannst es auch weglassen, aber weiß nicht ob das dann eventuell n Fehler produziert weil Bilder aus dem Pack in meiner Base hängen. Hatte es mal aus Versehen nicht reingeladen, da wurden die Bilder natürlich nicht korrekt angezeigt, ob im Logfile hinterher n Fehler aufgetaucht ist weiß ich allerdings nicht.

**Comment by Uraneptus** [comment]
Alles klar, danke! Ich werd mir das mal anschauen, gerne auch mit dem texturepack ^^
Ich werd da wahrscheinlich aber erst morgen zu kommen!
Ich wünsche dir noch einen schönen Sonntag Nachmittag!

**Comment by Uraneptus** [comment]
Ich guck mir das grade an. Bei mir fängt die Trap auch nix, also werd ich jetzt mal verschiedenes ausprobieren. Ich werd die Nachricht hier bearbeiten, wenn ich was neues weiß.
Deine Base ist übrigens echt hübsch, bin ein großer Fan, wie du das Feld gestaltet hast ^^

edit: Okay, ganz seltsame Sache. Ich hab Fishermen's Trap jetzt nochmal neu runtergeladen (mit Curseforge launcher, sollte aber keinen Unterschied machen) und jetzt funktioniert der Mod wieder. Wann und wo hast du den Mod heruntergeladen?

edit2: Hattest du nicht gesagt, dass du irgendwann die tag datei geändert hast, die entscheidet, in welchem Biom Fisch gefangen werden kann? Wie hattest du das genau gemacht?

**Comment by Leichenengel** [comment]
>>Deine Base ist übrigens echt hübsch, bin ein großer Fan, wie du das Feld gestaltet hast ^^<<

Danke. Ich dachte ich mach mal was anderes. normalerweise bau ich in nem Plains-Biom oder nem anders gearteten halbwegs baum- und bergfreien Gebiet allerdings in nähe zu nem Wald oder Wasser. Diesmal hab ich gedacht ich bau mal was in einen Berg rein in nem baumreichen Gebiet. Hab ne vorgenerierte Höhle ohne offensichtlichen Anschluss zu einem Höhlensystem genommen und die verschiedenen "Räume" der Höhle als Zimmer genutzt und vorne vor halt noch was Hausartiges damits etwas plastischer wirkt. Die Felder hab ich auch anders gemacht wie sonst. Sonst hatte ich immer sehr große Felder, aber durch den Farmer's Delight Mod und die erhöhte Random Tick Rate brauch ich nimmer so riesige Felder und muss demzufolge auch nicht viel terraformen. Ich bau nicht ganz so fancy und verschnörkelt mit Stufen und Slabs und Gedöns wie andere, aber nutze gerne verschiedene Blöcke und Blockfarben/muster. Auf meiner vorherigen Karte auf der mir das Problem mit den Fallen erstmals aufgefallen ist hab ich noch ne andere Modzusammenstellung benutzt. Einige auch mit in die neue Karte übernommen, aber z.B. Biomes o Plenty durch Terralith ausgetauscht und Pam's Harvestcraft durch Farmer's Delight und ein paar Addons davon. Meinen Create-Spielplatz werd ich mir woanders hintackern. Hab keine Erfahrung mit dem Mod und seinen Erweiterungen und muss mir erst Anfängervideos reinzihene. Hab mir gestern ne Abhandlung über Steam Engines aus Create reingezogen danach war ich nicht wesentlich schlauer und hatte das Gefühö man muss Mathematiker oder Physiker sein um den Mod zu verstehen :'D *hust* Ok nun aber zurück zum Thema Fischfallen...

>>edit: Okay, ganz seltsame Sache. Ich hab Fishermen's Trap jetzt nochmal neu runtergeladen (mit Curseforge launcher, sollte aber keinen Unterschied machen) und jetzt funktioniert der Mod wieder. Wann und wo hast du den Mod heruntergeladen?<<

Wann... vor ein paar Wochen wo ich wieder mit MC angefangen habe nach mehreren Jahren Pause. Runterladen tue ich Mods grundsätzlich nur auf Curseforge oder seltener auf Modrinth wenn in den Beschreibungen drinsteht, dass Updates nur noch da angeboten werden. Ich benutze keine anderen Quellen und ich nehme immer den aktuellsten DL für die Version die ich spiele und schaue auch immer nach Dependencies. Den Curse-Launcher benutze ich nicht, ich benutze den ganz normalen von Mojancrosoft :'D

>>edit2: Hattest du nicht gesagt, dass du irgendwann die tag datei geändert hast, die entscheidet, in welchem Biom Fisch gefangen werden kann? Wie hattest du das genau gemacht?<<

In den Kommentaren auf curseforge rätst du irgendwo irgendeinem Nutzer in der jar des mods in irgendeiner Datei (hab jetzt nicht genau aufm Schirm wie sie heißt) das Biom einzufügen wo die Trap Fische fangen können soll, weil der wohl in nem Plains Biom gebaut hat und der Fluss neben seiner Base nur kosmetisch ist, aber kein offizielles Fluss Biom. Zusätzlich hast du ihm geraten, falls das nicht funktioniert oder er es generell auf alle Biome beziehen will in der gleichen Datei den "is_overworld" tag einzubinden. Der Spieler hat sich danach nicht mehr gemeldet soweit ich mich entsinne, was für mich entweder heißt er ist happy und kann jetzt in seinem kosmetischen Fluss Fische fangen, oder er hats aufgegeben und sich n anderen Mod gesucht. Hab mich genau an die (natürlich sehr spärliche) Anleitung gehalten. Wurde beim Speichern auch gefragt ob die Datei überschrieben werden soll, da ich das jar-Archiv ja nicht vorher aufgelöst habe. Hab ja geclickt und dann hat er die datei überschrieben, bin aus der jar raus, hab sie im mod-ordner ersetzt, Spiel neugestartet - und nix hatte sich geändert. Auf die Idee n frischen Mod-Download ohne die Änderung zu versuchen bin ich auch gekommen. Keine Veränderung ^^

Edit 1: Hab jetzt den Mod nochmal neu runtergeladen und werde schauen ob's klappt. Melde mich dann in beiden Fällen (also ob oder ob nicht)

Edit 2: LOL - Jetzt fängt sie was. Und das Lustigste daran ist, dass ich vorher noch sehr weit weg von zu Hause war und mich dann dahin geportet habe um zu schauen. Da war viellecht 1 Minute vergangen und dann waren da schon Fische drin. Scheinbar war die "Anleitung" in deinem Kommentar echt zu spärlich und ich hab irgendwas verkehrt gemacht und dann bei der Zusammenstellung von Mods für die neue Karte die "bearbeitete" jar genommen statt der frischen die ich auf der alten Karte zwischenzeitlich versucht habe. Womöglich verändert Biomes O Plenty so viel an den Biomen, dass selbst die als Mincraft: River ausgezeichneten Biome nicht mehr als solche vom Mod erkannt werden, da kann ich nix zu sagen.

Frage: Soll die Falle Stacks bilden in den Slots, oder fängt die wirklich pro Slot nur 1 Fisch? Momentan sind in jeder Falle 3 Slots mit je 1 Fisch belegt und Fische können ja theoretisch bis 64 gestackt werden...

**Comment by Uraneptus** [comment]
Bezüglich der Anleitung die du meinst, war das weniger eine Anleitung und mehr ein abstrakter Hinweis. Ich bin in dem Kommentar, davon ausgegangen, dass die Person weiß wie man einen tag ändert, da dies jetzt schon seit einigen Jahren in Minecraft geändert wurde. Dabei hab ich aber nicht drüber nachgedacht, dass eventuell einige Leute die Änderungen in den letzten Jahren nicht mitverfolgt haben. Da muss ich mich mal kurz für entschuldigen 😅

Ich werd das ganze jetzt einmal etwas ausführlicher erklären:
Also seit einigen Mc Versionen ist Vieles, dass früher sehr stark an den Code gebunden war nun als mehr oder weniger externe Dateien geknüpft. Darunter fällt eigentlich alles, was man im data/ Ordner finden kann. Diese Änderungen sollen bewirken, dass mehr Leute ihr Spielerlebnis individueller gestalten können. Der Spieler hat jetzt die Möglichkeit ein [Datapack](https://minecraft.wiki/w/Data_pack) zu erstellen um diese ganzen Daten zu ändern und dieses dann in den Datapacks Ordner ihrer Welt hinzuzufügen. Wie man ein Datapack erstellt wird [hier](https://minecraft.wiki/w/Tutorials/Creating_a_data_pack#Setting_up_your_data_pack) ein bisschen erklärt, aber sonst gibt es auch viele Tutorials auf Youtube und ähnlichen Plattformen!

Was du gemacht hast ist eher unüblich und ich würde es für die Zukunft nicht empfehlen, obwohl es natürlich auch funktionieren würde. Du hast in der bearbeiteten Datei nur ein Komma vergessen, weshalb die Fishtrap nicht fischen konnte. 
Warum es allerdings mit Biomes O Plenty nicht funktioniert hat, muss ich mir noch anschauen, aber Hauptsache der Mod funktioniert jetzt wieder für dich!

Zu deiner Frage: Die Fishtrap kann pro Slot nur ein Item beinhalten

**Comment by Leichenengel** [comment]
Ja, also das nur 1 Fisch pro Slot geht hab ich schon gemerkt. Jetzt wo sie definitiv fischt werd ich die Zeit wieder hoch setzen, weil momentan kann ich gar nicht so schnell leeren und Köder nachlegen :D Schade, dass die Falle nicht stackt....

Was das verändern angeht hätte ich schon ein paar Ideen, aber bin programmiertechnisch eigentlich ein totaler Noob. Ich hab mich nie drum geschert wie MC nun genau programmiert ist - hab nur immer die bewundert die programmieren können. Mein Onkel hats jahrelang versucht mir erfolglos näher zu bringen. Hab's in 3 Programmiersprachen (Turbo Pascal, C++, Python) und einer Datenbanksprache (SmallTalk) nie über das "Hallo Welt"-Stadium hinaus geschafft. Die einzige "Programmiersprache" die ich mir mal so einigermaßen angeeignet habe war damals HTML3. HTML5 ist mir schon wieder zu komplex mit dem eingebundenen CSS und so, aber kann in bestehendem Code zumindest Dinge wiedererkennen und deuten was die in etwa machen. Aber selber n Front- oder Backend zusammenbasteln? Vergiss es...ich bin Printler...Visitenkarten, Flyer, Poster, kein Problem - aber den Digitalen Teil von Digital&Print.....ohne mich. Ein Grund, warum ich in meinem Ausbildungsberuf nicht arbeite. Heutzutage wollen Agenturen Überflieger haben die sie an den Rechner setzen können und alles läuft....

Ich würde also der Falle für mein Spielerlebnis gerne Stacks hinzufügen. So 16er-Stacks pro Slot würden mir ja schon langen oder auch nur 8er. Dann muss ich mich nicht alle 2 Minuten um die dinger kümmern :D

Weiterhin würde ich gerne den Bait-Table etwas erweitern, was ja im Wiki für Datapacks einigermaßen beschrieben ist, aber bin wie gesagt keine Programmier-Leuchte. Beeren für Lachs sind okay - Beeren schmeißt einem das Spiel praktisch hinterher. Von Rüben erntet man pro Pflanze immer nur eine, was irgendwie doof ist, da man von Karotten und Kartoffeln auch mehrere bekommt (allerdings keine Samen ja ich weiß). Schätze die Rüben sind an Weizen angelehnt wo man auch nur 1 Garbe bekommt und mehrere Samen. Da Fische in der Realität eher kleine pflanzliche Nahrung zu sich nehmen, oder je nach Fisch auch andere Fische oder Krebsgetier, würde ich dem Bait table für Lachs gern Rübensamen und dem für Kabeljau/Dorsch Weizensamen hinzufügen. Wenn's in Minecraft Würmer und Käfer gäbe, würde ich auch die nehmen XD. Für Tropische Fische würde ich neben Melonenscheiben noch Melonensamen oder Kürbissamen dazu nehmen oder auch Seetang als möglichen Köder verwenden. Das sind die einzigen 3 Fischsorten die nahrungstechnisch zu was taugen und der tropische fisch auch nur weil ich Crabber's Delight nutze. Wobei sein Nutzen da auch stark begrenzt ist.

Man könnte z.B. soweit gehen noch ein Loot für Treasure zu definieren was dann aber auch nen anderen Loot Table benötigen würde wo nur items gelistet sind, die wirklichen Wert haben, wie z.B. Roherze, Schatzkarten, gute Tränke, etc.

Entweder ich finde irgendwo ein schon fertiges Data Pack oder ich muss java lernen <.< (wird in diesem Leben vermutlich eher nicht mehr passieren, da ich weiß wie es mit den anderen Programmiersprachen geendet ist...)

**Comment by Uraneptus** [comment]
Deine Pläne klingen aufjedenfall gut. Ich kann demnächst, wenn ich die Zeit dazu finde auf der Wiki Seite dieses Mods ein paar Beispiel datapacks hochladen. Ich glaube, dass könnte einigen sehr helfen! 
Die Stack size kann ich aber leider nicht verändern (und mit datapacks ist das auch nicht möglich), da das eine wichtige Design Choice war.
Zum Thema Programmieren, muss ich dir recht geben, dass ist nicht für jeden was. Vor allem, weil sich die verschieden Sprachen meist relativ schnell entwickeln und verändern,

**Comment by Leichenengel** [comment]
Mein Pläne wären ja ggf. auch was für ein offizielles Update. auf die Weise haben Spieler mehr Optionen, wie sie ihre Köder gestalten wollen und können dann wenn sie Bock haben selber halt Datapacks bauen für Köder aus anderen Mods. Aber ich denke dazu mache ich am besten ein neues Topic auf. Da der Mod jetzt funktioniert, kann das hier jetzt von mir aus geschlossen werden, außer du willst es noch offen lassen, weil du dir die Kompatibilität mit BoP noch angucken magst, oder so. In BoP hatte ich den Mod ja ursprünglich auch unbearbeitet und sie hat trotz Minecraft: River Biome nicht funktioniert. Daher habe ich halt das mit dem is_overworld ausprobiert (und das Komma vergessen) und dann halt n Kommentar auf Curseforge geschrieben. Dass das mit den Stacks nicht geht ist schade, aber nun ja, dann ist das so. Danke für den Support, auch wenn das erneut Herunterladen und vermutlich die neue Modzusammenstellung ebenfalls geholfen hatten. Ich hatte wohl nur die korrupte Moddatei einbezogen statt der frischen. Nun ja, passiert.

**Comment by Uraneptus** [comment]
Ob deine Ideen in ein offizielles Update kommen, kann ich leider nicht entscheiden! Ich werd sie aber an den Owner des Mods weiter leiten! Ich werd dieses Issue gleich schließen. Schönen Abend noch ^^
