### ISSUE TITLE
Can we have configureable biome requirement?

### ISSUE THREAD

**Issue by xXStrayXx** [Uraneptus/Fishermens-Trap#20]
Because I'm having trouble using this mod in skyblock......

**Comment by Uraneptus** [comment]
You can just configure the data files for this

**Comment by xXStrayXx** [comment]
oh wow thanks!

**Comment by Helpful-Neko** [comment]
> You can just configure the data files for this

I was having a similar issue with the biome restrictions. I built a little fishing cabin but didn't realize it wasn't in a river or ocean biome. Is there a way to configure the mod to ignore the biome restrictions on my server?
