### ISSUE TITLE
Modded water biomes don't count for fishermans trap to work?

### ISSUE THREAD

**Issue by ZephyrWindSpirit** [Uraneptus/Fishermens-Trap#4]
I may be uninformed on the specifics of how the trap should be placed beside 'submerged'. 

I have mine in the twilight stream in the twilight forest. Not sure if this counts for a water biome. But if it does not, could that be added, or any twilight water biome?

**Comment by Uraneptus** [comment]
The fish trap works in every biome that is in the `forge:is_water` tag. If the twilight stream is inside this tag then it should work.

**Comment by SiverDX** [comment]
twilight forest decided against putting their biomes in the forge tags to prevent non-twilight-forest mobs from spawning in them iirc (saw it in some code comments in their github)

**Comment by Uraneptus** [comment]
Good to know thanks!
In that case I'm sadly not able to do anything about this issue. However you can always add the Twilight Forest biomes to the forge tag yourself and it should work. (If not, don't hesitate and let me know!)

**Comment by ZephyrWindSpirit** [comment]
I personally don't know how that works for adding to forge tags but glad to know it's not a 'me only' problem. 
Still makes a cute decor block.
