### ISSUE TITLE
Inserting into bait slot crashes game [Modpack]

### ISSUE THREAD

**Issue by Rytelus** [Uraneptus/Fishermens-Trap#6]
While playing the Raspberry Flavored modpack I tried using a hopper and Quark Oddities pipes to insert bait but this ended up crashing the game and making the world unplayable until I used NBT Explorer to nuke the pipe system. Moreover, all methods of inserting bait such as Create chutes, hoppers, and item pipes crashed the game. Extracting items from below worked normally. The pack devs said to report this issue here, but it should be noted I was unable to recreate this issue with just Fishermen's trap installed by itself.

[---- Minecraft Crash Report ----.txt](https://github.com/Uraneptus/Fishermens-Trap/files/12270297/----.Minecraft.Crash.Report.----.txt)
![image](https://github.com/Uraneptus/Fishermens-Trap/assets/42482386/607b4433-d942-4bc9-9290-75b1183f87cc)

**Comment by Uraneptus** [comment]
Does this still happen with version 1.3.1?
Because I tried fixing this after the curseforge comment.

**Comment by Rytelus** [comment]
Yeah, I updated the mod to that version and the crashes stopped happening! Thank you very much.

**Comment by Uraneptus** [comment]
You're welcome!
