### ISSUE TITLE
Simple DataPack creation - LootTable not work...

### ISSUE THREAD

**Issue by Maruhl** [Uraneptus/Fishermens-Trap#9]
Hi, ich spare mir mal das englisch gequatsche.

Ich versuche gerade ein DataPack zu bauen, genau wie es im Wiki steht - Keine Ahnung wie das alles intern funktioniert.

Ich möchte eine Verbindung zum Mod "Aquaculture 2" bewerkstelligen, wo man diverse Fischhaken in die Falle legt,
und danach der Loot von dem Mod rein kommt.
Die Haken lassen sich bereits in der Falle setzen. Aber der Loot kommt nicht.

Das DataPack habe ich mal [Link](https://github.com/Maruhl/MC-DP-FT_AC2) hochgeladen.
Alles nur zum probieren und gugn wie es funktioniert.

Vielleich kannst du mir ein Tip geben woran es liegt. Im Moment ist nur die LootTable für "iron_hook.json" implementiert.
Am Ende geht es mit dem Mod (mit DataPack) garnicht.

Genutzt wird:
- 1.20.1-forge-47.2.0
- fishermens_trap-2.1.1
- Aquaculture-1.20.1-2.5.0.

**Comment by Uraneptus** [comment]
Hmm okay, das muss ich später mal genauer testen. Hast du nachgeschaut ob du im richtigen biome bist? Und wie lange hast du ca auf den loot gewartet?

**Comment by Maruhl** [comment]
Moin, ich habe etwa 30min im "minecraft:river"-Biom gewartet, und das ist das Ergebnis:

![grafik](https://github.com/Uraneptus/Fishermens-Trap/assets/41585619/0d4c9b2a-400e-423d-af5f-6d28cca0d329)

Update: Im oberen war ein "Brot" drinne, deswegen ist da ein Fisch - nicht wundern.

**Comment by Uraneptus** [comment]
Danke

**Comment by Uraneptus** [comment]
Hab herausgefunden, was das Problem war. 
![image](https://github.com/Uraneptus/Fishermens-Trap/assets/50745606/2d408c32-667e-4fcf-8554-9acbea563660)

Du hast in the loot table als letzten Eintrag `"aquaculture:neptunes_bounty_loot"` geschrieben. Es gibt aber kein Item mit dieser id.
Es gibt `"aquaculture:neptunes_bounty"`, was halt diese Kiste ist. Ich weiß nicht viel von aquaculture, also wenn du mit  `"aquaculture:neptunes_bounty_loot"` etwas bestimmtes erzielen wolltest, dann sag bescheid, vielleicht kann ich da nochmal helfen!

**Comment by Uraneptus** [comment]
Du musst aufjeden fall immer aufpassen, dass alles was du in die loot table schreibst korret ist. Wenn auch nur eine Kleinigkeit falsch ist, wird die loot table nicht geladen!

**Comment by Maruhl** [comment]
Hi, danke fürs nachschauen. Ja, das wars wirklich.
Ich habe ein wenig rum probiert. Zum einen ist es ungünstig das immer ein Haken verbraucht wird. Da einige Haken relativ teuer werden könnten. Kann man das in diesem Fall abstellen?

In dem Mod kann man natürlich auch noch diese `"aquaculture:neptunes_bounty"` bekommen. Wenn ich diese in die json eintrage, kommt auch diese Box, ist aber leider schon getagged. Das heißt, diese Kiste ist Leer.

[Code](https://github.com/TeamMetallurgy/Aquaculture/blob/master/src/main/java/com/teammetallurgy/aquaculture/block/NeptunesBountyBlock.java)

Die Mechanik sieht eigentlich vor, dass man diese besondere Box angeln kann. Wo dann relative gute Items randomized enthalten sind - beim aufmachen. Ich kenne mich mit dem Code nicht aus, Java ist nicht mein Fall und Forge-API schon garnicht.
Man müsste also dann den Tag "BlockEntityTag.Items" an der Box entfernen - Vermutlich, damit dann randomized Items raus kommen.

Ich habe mir nicht angeschaut wie dein Mod das angeln bewerkstelligt, aber dieses "alte Mod" 
[Code](https://github.com/kylertlove/fish-traps) hat das Biom und dessen Fishing-Loottable beachtet.

Zumindest war es so mit allen anderen Fishing Mods kompatibel.

**Comment by Uraneptus** [comment]
Wie hast du die neptunes_bounty in this loot table eingebaut?
Bezüglich der sich abnutzenden Haken, könnte ich eventuell demnächst eine mechanic einbauen, die die haltbarkeit reduziert

**Comment by Maruhl** [comment]
Naja, normal in der json eingetragen.
Dafür habe ich einen neuen Eintrag in die "gold_hook.json" mit "weight=100" gemacht, nur um zu testen.

Aber wie gesagt, es bringt nichts, da diese Box nicht mit "random" items gefüllt ist, wie es normalerweiße wäre wenn man angelt.

**Comment by Uraneptus** [comment]
Du musst das in die json eintragen, wie im angehängten bild beschrieben:
![Screenshot_2023-11-14-21-40-15-933_com.github.android.jpg](https://github.com/Uraneptus/Fishermens-Trap/assets/50745606/555fe185-4ac6-427a-a268-c8ad7e4fec88)

Das ist ein Screenshot von der fishing loot table aus aquaculture 2
